<?php
// @codingStandardsIgnoreFile
/* @var $block \Aheadworks\Sarp2\Block\Customer\Subscriptions\Edit\View\PaymentDetails\AbstractCreditCardRenderer */
/* @var $token \Aheadworks\Sarp2\Api\Data\PaymentTokenInterface */
/* @var $tokenDetails array */
?>
<div class="credit-card wrapper">
    <div class="card-type">
        <img src="<?= /* @noEscape */ $block->getIconUrl($block->getCreditCardType($tokenDetails)) ?>"
             width="<?= /* @noEscape */ $block->getIconWidth($block->getCreditCardType($tokenDetails)) ?>"
             height="<?= /* @noEscape */ $block->getIconHeight($block->getCreditCardType($tokenDetails)) ?>"
        >
    </div>
</div>
